[package]
name = "kebab"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = {version = "4.5.54", features = ["derive"]}
reqwest = { version = "0.13.1", features = ["blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
